export const AC_LOGIN = 'Login'
export const MU_LOGIN = 'Login'
export const MU_CHECKFORBOTS = 'CheckForBots'

export const MU_ARTICLES_UPDATE_PAGING = 'Articles_Update_Paging'
export const MU_ARTICLES_UPDATE_TAGS_CATEGORIES = 'Articles_Update_Tags_Categories'
export const AC_ARTICLES_FETCH_ALL = 'Articles_Fetch_All'
export const AC_ARTICLES_FETCH_ALL_CATEGORIES_AND_TAGS = 'Articles_Fetch_All_Categories_And_Tags'
export const AC_ARTICLES_ADD_NEW = 'Articles_Add_New'
export const AC_ARTICLES_LOAD_ARTICLE = 'Articles_Add_Article'
